name: Comment metrics
# read-write repo token
on:
  workflow_run:
    workflows: [Build metrics]
    types: [completed]

jobs:
  comment-binary-size:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Download metrics summary
        uses: actions/github-script@v6
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "metrics-output"
            })[0];
            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/metrics-output.zip', Buffer.from(download.data));
      - name: Unzip file
        run: sudo apt-get install unzip && unzip -o metrics-output.zip
      - name: Add comment
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var fs = require('fs');
            var pr_number = Number(fs.readFileSync('./PR_number'));
            var binary_size_summary = fs.readFileSync('./binary_size_summary');
            var app_sizes = fs.readFileSync('./app_sizes');
            var binary_size_model;
            var model;
            if (fs.existsSync('./binary_size_n0110')) {
              binary_size_model = fs.readFileSync('./binary_size_n0110');
              model = "N0110";
            } else if (fs.existsSync('./binary_size_n0120')) {
              binary_size_model = fs.readFileSync('./binary_size_n0120');
              model = "N0120";
            } else {
              throw new Error("No binary_size found for either N0120 or N0110 .");
            }

            const body = (
              "### Binary size analysis\n\n"
              + binary_size_summary + "\n"
              + "<details>\n<summary>Full details</summary>\n\n"
              + "### Apps\n\n"
              + app_sizes + "\n\n"
              + "### " + model + "\n\n"
              + binary_size_model + "\n"
              + "</details>"
            );

            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const oldComments = await github.paginate(
              github.rest.issues.listComments,
              {
                owner, repo,
                issue_number: pr_number,
              }
            );

            const commentToUpdate = oldComments.findLast(comment =>
              comment.user.login === 'github-actions[bot]' && comment.body.startsWith(body.slice(0,10))
            )

            if (commentToUpdate) {
              await github.rest.issues.updateComment({
                owner, repo, body,
                comment_id: commentToUpdate.id,
              });
            } else {
              await github.rest.issues.createComment({
                owner, repo, body,
                issue_number: pr_number,
              });
            }
